sudo: true
cache:
 bundler: true
language: ruby
rvm:
 - 2.3.0
services:
  - postgresql
env:
- DB=postgres
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database my_database_test;' -U postgres
script: TESTOPTS="--verbose" bundle exec rake test