language: ruby
sudo: required
addons:
  postgresql: "9.3.14"
  code_climate:
  repo_token:
services:
  - postgresql

rvm:
   - "2.3.0"
before_script:
  - cp config/database.yml
  - psql -c 'create database my_database_test;' -U postgres
script: TESTOPTS=