language: ruby
rvm:
   - "2.3.0"
sudo: required
cache: bundler
addons:
  postgresql: "9.3.14"
  code_climate:
  repo_token: f51d853f26b3ae635f96bb8cb9b439e7137a27fc0b8ea005aa046c17054a9d85
services:
  - postgresql
  - redis
before_script:
  - bundle exec rake db:setup
  - bundle exec rspec spec/models/user_spec.rb
after_success:
  - bundle exec codeclimate-test-reporter